# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f03baeafae1c5498a33fd1ef192ff91ef51d57be086e8cd3cdfa80a8245f79f8f8376eda90d2617e51d3350637d7dbb18e4fb041cef21647f692e12dbb64899

test:
  secret_key_base: c7f33036f337372c7714fdda8a7c314d55957e4c09728a780c90d7ec2e1951c771b61faa744e1c8e2e2be3dda3d2888b0ae60ff9e92c2b2e992c2b01c4e390cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
